-- Private Client Property Desk — full cloud bootstrap (001–014)
-- Run once in Supabase SQL Editor on a new project.

-- ========== 001_initial.sql ==========
-- Astoria AI Home Match — initial schema

create extension if not exists "pgcrypto";

create table if not exists public.leads (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  lead_type text not null check (lead_type in ('buyer', 'seller')),
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text,
  preferred_contact_method text not null,
  consent_given boolean not null default false,
  quiz_data jsonb not null,
  ai_report jsonb not null,
  lead_score integer not null check (lead_score >= 0 and lead_score <= 100),
  lead_temperature text not null check (lead_temperature in ('cold', 'warm', 'hot')),
  internal_lead_summary text not null,
  suggested_follow_up_message text not null,
  status text not null default 'new' check (
    status in ('new', 'contacted', 'booked', 'closed', 'not qualified')
  )
);

create table if not exists public.lead_events (
  id uuid primary key default gen_random_uuid(),
  lead_id uuid not null references public.leads (id) on delete cascade,
  created_at timestamptz not null default now(),
  event_type text not null,
  event_data jsonb
);

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_lead_type_idx on public.leads (lead_type);
create index if not exists leads_lead_temperature_idx on public.leads (lead_temperature);
create index if not exists lead_events_lead_id_idx on public.lead_events (lead_id);

alter table public.leads enable row level security;
alter table public.lead_events enable row level security;

-- MVP: no public policies — server uses service role only
create policy "No public access to leads"
  on public.leads
  for all
  using (false)
  with check (false);

create policy "No public access to lead_events"
  on public.lead_events
  for all
  using (false)
  with check (false);

-- ========== 002_phase2_attribution_and_tokens.sql ==========
-- Phase 2: public result tokens, attribution, admin notes

alter table public.leads
  add column if not exists public_result_token text unique,
  add column if not exists utm_source text,
  add column if not exists utm_medium text,
  add column if not exists utm_campaign text,
  add column if not exists utm_term text,
  add column if not exists utm_content text,
  add column if not exists landing_page text,
  add column if not exists referrer text,
  add column if not exists user_agent text,
  add column if not exists gclid text,
  add column if not exists fbclid text,
  add column if not exists admin_notes text;

create index if not exists leads_public_result_token_idx
  on public.leads (public_result_token);

create index if not exists leads_utm_source_idx on public.leads (utm_source);
create index if not exists leads_status_idx on public.leads (status);

-- ========== 003_report_source.sql ==========
-- Track whether AI report was generated by OpenAI or fallback logic

alter table public.leads
  add column if not exists report_source text
    check (report_source in ('openai', 'fallback'));

create index if not exists leads_report_source_idx on public.leads (report_source);

-- ========== 004_equity_lead_type.sql ==========
-- Support equity Move Up Plan leads

alter table public.leads drop constraint if exists leads_lead_type_check;

alter table public.leads add constraint leads_lead_type_check
  check (lead_type in ('buyer', 'seller', 'equity'));

-- ========== 005_wealth_forecast_lead_type.sql ==========
-- Support Real Estate Wealth Forecast leads

alter table public.leads drop constraint if exists leads_lead_type_check;

alter table public.leads add constraint leads_lead_type_check
  check (lead_type in ('buyer', 'seller', 'equity', 'wealth_forecast'));

-- ========== 006_site_analytics.sql ==========
-- First-party website activity tracking (anonymous until lead submission)

create table if not exists public.site_events (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  session_id text not null,
  lead_id uuid references public.leads (id) on delete set null,
  event_name text not null,
  page_path text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  gclid text,
  fbclid text,
  metadata jsonb not null default '{}'::jsonb,
  user_agent text,
  ip_hash text
);

create index if not exists site_events_created_at_idx
  on public.site_events (created_at desc);

create index if not exists site_events_session_id_idx
  on public.site_events (session_id);

create index if not exists site_events_lead_id_idx
  on public.site_events (lead_id);

create index if not exists site_events_event_name_idx
  on public.site_events (event_name);

create index if not exists site_events_page_path_idx
  on public.site_events (page_path);

create index if not exists site_events_utm_source_idx
  on public.site_events (utm_source);

create index if not exists site_events_utm_campaign_idx
  on public.site_events (utm_campaign);

alter table public.site_events enable row level security;

create policy "No public access to site_events"
  on public.site_events
  for all
  using (false)
  with check (false);

-- ========== 007_multi_tenant_core.sql ==========
-- Multi-tenant core: tenants table + tenant scoping columns

create table if not exists public.tenants (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  brand_name text not null,
  agent_name text not null,
  agent_title text,
  brokerage_name text,
  agent_license_number text,
  brokerage_license_number text,
  notification_email text,
  contact_email text,
  phone text,
  booking_url text,
  logo_url text,
  primary_color text,
  accent_color text,
  supported_states text[] not null default array['CA']::text[],
  service_areas text[] not null default array[]::text[],
  default_state text not null default 'CA',
  disclaimer_text text,
  seo_base_title text,
  seo_base_description text,
  custom_domain text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.tenants enable row level security;

create policy "No public access to tenants"
  on public.tenants
  for all
  using (false)
  with check (false);

insert into public.tenants (
  slug,
  brand_name,
  agent_name,
  brokerage_name,
  agent_license_number,
  brokerage_license_number,
  supported_states,
  service_areas
)
values (
  'astoria',
  'Astoria Luxury Estates',
  'Justin Kuo',
  'Real Brokerage Technologies',
  'California DRE 02113892',
  'California DRE 02022092',
  array['CA']::text[],
  array[
    'Newport Beach',
    'Irvine',
    'Costa Mesa',
    'Laguna Beach',
    'Orange County'
  ]::text[]
)
on conflict (slug) do update
set
  brand_name = excluded.brand_name,
  agent_name = excluded.agent_name,
  brokerage_name = excluded.brokerage_name,
  agent_license_number = excluded.agent_license_number,
  brokerage_license_number = excluded.brokerage_license_number,
  supported_states = excluded.supported_states,
  service_areas = excluded.service_areas,
  updated_at = now();

alter table public.leads
  add column if not exists tenant_id uuid references public.tenants(id);

update public.leads
set tenant_id = t.id
from public.tenants t
where t.slug = 'astoria'
  and public.leads.tenant_id is null;

create index if not exists leads_tenant_id_idx
  on public.leads (tenant_id);

alter table public.site_events
  add column if not exists tenant_id uuid references public.tenants(id);

update public.site_events
set tenant_id = t.id
from public.tenants t
where t.slug = 'astoria'
  and public.site_events.tenant_id is null;

create index if not exists site_events_tenant_id_idx
  on public.site_events (tenant_id);

-- ========== 008_demo_tenant.sql ==========
-- Seed a second demo tenant for isolation verification

insert into public.tenants (
  slug,
  brand_name,
  agent_name,
  agent_title,
  brokerage_name,
  agent_license_number,
  brokerage_license_number,
  notification_email,
  contact_email,
  phone,
  booking_url,
  supported_states,
  service_areas,
  default_state,
  disclaimer_text
)
values (
  'demo-agent',
  'Demo Luxury Realty',
  'Sarah Morgan',
  'Luxury Real Estate Advisor',
  'Demo Brokerage',
  'California DRE 00000000',
  'California DRE 11111111',
  'demo@example.com',
  'demo@example.com',
  '5555555555',
  'https://example.com/book-demo-agent',
  array['CA']::text[],
  array['Newport Beach', 'Irvine', 'Laguna Beach', 'Orange County']::text[],
  'CA',
  'Sarah Morgan will provide licensed California real estate guidance before any buying or selling decision. Demo Luxury Realty currently supports California real estate inquiries only.'
)
on conflict (slug) do update
set
  brand_name = excluded.brand_name,
  agent_name = excluded.agent_name,
  agent_title = excluded.agent_title,
  brokerage_name = excluded.brokerage_name,
  agent_license_number = excluded.agent_license_number,
  brokerage_license_number = excluded.brokerage_license_number,
  notification_email = excluded.notification_email,
  contact_email = excluded.contact_email,
  phone = excluded.phone,
  booking_url = excluded.booking_url,
  supported_states = excluded.supported_states,
  service_areas = excluded.service_areas,
  default_state = excluded.default_state,
  disclaimer_text = excluded.disclaimer_text,
  updated_at = now();

-- ========== 009_tenant_logos_storage.sql ==========
-- Tenant logos storage bucket and read policy

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'tenant-logos',
  'tenant-logos',
  true,
  2097152,
  array['image/png', 'image/jpeg', 'image/webp']::text[]
)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Public read tenant logos'
  ) then
    create policy "Public read tenant logos"
      on storage.objects
      for select
      using (bucket_id = 'tenant-logos');
  end if;
end $$;

-- ========== 010_tenant_domains.sql ==========
-- Tenant custom domains and platform subdomains

create table if not exists public.tenant_domains (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  domain text not null unique,
  domain_type text not null default 'custom_domain',
  status text not null default 'pending',
  verification_token text,
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tenant_domains_status_check
    check (status in ('pending', 'verified', 'active', 'failed')),
  constraint tenant_domains_type_check
    check (domain_type in ('platform_subdomain', 'custom_domain'))
);

create index if not exists tenant_domains_tenant_id_idx
  on public.tenant_domains (tenant_id);

create index if not exists tenant_domains_domain_idx
  on public.tenant_domains (domain);

alter table public.tenant_domains enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'tenant_domains'
      and policyname = 'No public access to tenant_domains'
  ) then
    create policy "No public access to tenant_domains"
      on public.tenant_domains
      for all
      using (false)
      with check (false);
  end if;
end $$;

-- ========== 011_lead_pipeline_crm.sql ==========
-- Lead pipeline CRM: status tracking, follow-ups, deal value, and comment history

alter table public.leads
  add column if not exists lead_status text not null default 'new',
  add column if not exists last_contacted_at timestamptz,
  add column if not exists next_follow_up_at timestamptz,
  add column if not exists lead_notes text,
  add column if not exists lost_reason text,
  add column if not exists estimated_deal_value numeric,
  add column if not exists estimated_commission numeric,
  add column if not exists closed_at timestamptz;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'leads_lead_status_check'
  ) then
    alter table public.leads
      add constraint leads_lead_status_check
      check (lead_status in (
        'new',
        'contacted',
        'appointment_scheduled',
        'listing_appointment',
        'buyer_consultation',
        'active_client',
        'under_contract',
        'closed',
        'lost'
      ));
  end if;
end $$;

create index if not exists leads_lead_status_idx
  on public.leads (lead_status);

create index if not exists leads_next_follow_up_at_idx
  on public.leads (next_follow_up_at);

create index if not exists leads_closed_at_idx
  on public.leads (closed_at);

create table if not exists public.lead_comments (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  lead_id uuid not null references public.leads(id) on delete cascade,
  comment_text text not null,
  comment_type text not null default 'note',
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  constraint lead_comments_type_check
    check (comment_type in (
      'note',
      'call',
      'sms',
      'email',
      'meeting',
      'status_change',
      'system'
    ))
);

create index if not exists lead_comments_tenant_id_idx
  on public.lead_comments (tenant_id);

create index if not exists lead_comments_lead_id_idx
  on public.lead_comments (lead_id);

create index if not exists lead_comments_created_at_idx
  on public.lead_comments (created_at);

alter table public.lead_comments enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'lead_comments'
      and policyname = 'No public access to lead_comments'
  ) then
    create policy "No public access to lead_comments"
      on public.lead_comments
      for all
      using (false)
      with check (false);
  end if;
end $$;

-- ========== 012_ai_strategy_room.sql ==========
-- Private Client Property Desk — AI Strategy Room demo layer

alter table public.leads
  add column if not exists ai_strategy_room jsonb,
  add column if not exists ai_scenario_comparison jsonb,
  add column if not exists ai_advisor_coordination_map jsonb,
  add column if not exists ai_advisor_specific_briefs jsonb,
  add column if not exists ai_deal_readiness jsonb,
  add column if not exists ai_relationship_map jsonb,
  add column if not exists ai_meeting_prep_pack jsonb,
  add column if not exists ai_white_glove_follow_up jsonb,
  add column if not exists ai_red_flags_missing_info jsonb,
  add column if not exists ai_presentation_mode jsonb,
  add column if not exists ai_demo_version text default 'strategy-room-v1',
  add column if not exists ai_generated_at timestamptz,
  add column if not exists ai_generation_source text,
  add column if not exists ai_generation_model text;

create index if not exists leads_ai_generated_at_idx
  on public.leads (ai_generated_at desc nulls last);

-- ========== 013_private_client_tenant.sql ==========
-- Seed Private Client Property Desk as the default production tenant

insert into public.tenants (
  slug,
  brand_name,
  agent_name,
  agent_title,
  brokerage_name,
  notification_email,
  contact_email,
  phone,
  supported_states,
  service_areas,
  default_state,
  disclaimer_text,
  seo_base_title,
  seo_base_description
)
values (
  'private-client',
  'Private Client Property Desk',
  'Your Advisory Team',
  'Licensed Real Estate & Advisory Coordination',
  'Private Client Advisory Group',
  'leads@private-client-desk.local',
  'hello@private-client-desk.local',
  '(949) 555-5555',
  array['CA']::text[],
  array[
    'Newport Beach',
    'Irvine',
    'Costa Mesa',
    'Laguna Beach',
    'Orange County',
    'Aspen'
  ]::text[],
  'CA',
  'This private brief is for planning and coordination purposes only. It is not legal, tax, lending, investment, appraisal, or valuation advice. Tax topics should be reviewed with a CPA, legal and entity topics with an attorney, lending topics with a lender or private banker, and real estate execution topics with a licensed agent.',
  'Private Client Property Desk | AI Strategy Room',
  'AI-powered planning and coordination for complex real estate decisions involving agents, wealth advisors, CPAs, attorneys, and lenders.'
)
on conflict (slug) do update
set
  brand_name = excluded.brand_name,
  agent_name = excluded.agent_name,
  agent_title = excluded.agent_title,
  brokerage_name = excluded.brokerage_name,
  notification_email = excluded.notification_email,
  contact_email = excluded.contact_email,
  phone = excluded.phone,
  supported_states = excluded.supported_states,
  service_areas = excluded.service_areas,
  default_state = excluded.default_state,
  disclaimer_text = excluded.disclaimer_text,
  seo_base_title = excluded.seo_base_title,
  seo_base_description = excluded.seo_base_description,
  updated_at = now();

-- Backwards-compatible slug used by older links and localStorage keys
insert into public.tenants (
  slug,
  brand_name,
  agent_name,
  agent_title,
  brokerage_name,
  supported_states,
  service_areas,
  default_state,
  disclaimer_text,
  seo_base_title,
  seo_base_description
)
select
  'astoria',
  brand_name,
  agent_name,
  agent_title,
  brokerage_name,
  supported_states,
  service_areas,
  default_state,
  disclaimer_text,
  seo_base_title,
  seo_base_description
from public.tenants
where slug = 'private-client'
on conflict (slug) do update
set
  brand_name = excluded.brand_name,
  agent_name = excluded.agent_name,
  agent_title = excluded.agent_title,
  brokerage_name = excluded.brokerage_name,
  supported_states = excluded.supported_states,
  service_areas = excluded.service_areas,
  default_state = excluded.default_state,
  disclaimer_text = excluded.disclaimer_text,
  seo_base_title = excluded.seo_base_title,
  seo_base_description = excluded.seo_base_description,
  updated_at = now();

-- ========== 014_decision_graph_data_room_guardrails.sql ==========
-- Private Client Decision Layer — graph, data room, timeline, meeting notes

alter table public.leads
  add column if not exists ai_decision_graph jsonb,
  add column if not exists ai_compliance_guardrails jsonb,
  add column if not exists ai_decision_timeline_summary jsonb,
  add column if not exists ai_data_room_suggestions jsonb,
  add column if not exists decision_stage text default 'exploration';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'leads_decision_stage_check'
  ) then
    alter table public.leads
      add constraint leads_decision_stage_check
      check (decision_stage in (
        'exploration',
        'planning',
        'advisor_review',
        'execution_preparation'
      ));
  end if;
end $$;

create index if not exists leads_decision_stage_idx
  on public.leads (decision_stage);

create table if not exists public.decision_data_room_items (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references public.tenants(id) on delete cascade,
  lead_id uuid not null references public.leads(id) on delete cascade,
  category text not null,
  item_name text not null,
  description text,
  requested_from text,
  advisor_owner text,
  status text not null default 'not_requested',
  priority text not null default 'medium',
  visibility text not null default 'admin',
  due_date timestamptz,
  storage_path text,
  file_name text,
  file_mime_type text,
  file_size_bytes integer,
  ai_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint decision_data_room_status_check
    check (status in (
      'not_requested', 'requested', 'received', 'reviewed', 'not_needed'
    )),
  constraint decision_data_room_priority_check
    check (priority in ('low', 'medium', 'high')),
  constraint decision_data_room_visibility_check
    check (visibility in ('public', 'admin'))
);

create index if not exists decision_data_room_lead_id_idx
  on public.decision_data_room_items (lead_id);

create index if not exists decision_data_room_tenant_id_idx
  on public.decision_data_room_items (tenant_id);

create index if not exists decision_data_room_category_idx
  on public.decision_data_room_items (category);

create table if not exists public.decision_versions (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references public.tenants(id) on delete cascade,
  lead_id uuid not null references public.leads(id) on delete cascade,
  version_number integer not null,
  change_source text not null,
  changed_by text,
  previous_snapshot jsonb,
  new_snapshot jsonb,
  ai_change_summary jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists decision_versions_lead_version_idx
  on public.decision_versions (lead_id, version_number);

create index if not exists decision_versions_lead_id_idx
  on public.decision_versions (lead_id);

create table if not exists public.lead_meeting_notes (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references public.tenants(id) on delete cascade,
  lead_id uuid not null references public.leads(id) on delete cascade,
  note_title text,
  note_body text not null,
  meeting_date timestamptz,
  attendees jsonb not null default '[]'::jsonb,
  ai_summary jsonb,
  created_by text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lead_meeting_notes_lead_id_idx
  on public.lead_meeting_notes (lead_id);

alter table public.decision_data_room_items enable row level security;
alter table public.decision_versions enable row level security;
alter table public.lead_meeting_notes enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'decision_data_room_items'
      and policyname = 'No public access to decision_data_room_items'
  ) then
    create policy "No public access to decision_data_room_items"
      on public.decision_data_room_items for all using (false) with check (false);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'decision_versions'
      and policyname = 'No public access to decision_versions'
  ) then
    create policy "No public access to decision_versions"
      on public.decision_versions for all using (false) with check (false);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'lead_meeting_notes'
      and policyname = 'No public access to lead_meeting_notes'
  ) then
    create policy "No public access to lead_meeting_notes"
      on public.lead_meeting_notes for all using (false) with check (false);
  end if;
end $$;

-- Optional upload bucket foundation
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'private-client-data-room',
  'private-client-data-room',
  false,
  10485760,
  array[
    'application/pdf',
    'image/png',
    'image/jpeg',
    'image/webp',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  ]::text[]
)
on conflict (id) do update
set
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- ========== 016_data_room_upload_document_summary.sql ==========
-- Data Room document upload summary fields (admin-only)

alter table public.decision_data_room_items
  add column if not exists ai_document_summary jsonb,
  add column if not exists ai_document_summary_generated_at timestamptz,
  add column if not exists ai_document_summary_source text,
  add column if not exists ai_document_summary_model text;

-- ========== 017_advisor_action_board.sql ==========
-- Advisor Action Intelligence Board — lead columns + action items table

alter table public.leads
  add column if not exists ai_advisor_action_board jsonb,
  add column if not exists ai_advisor_action_board_generated_at timestamptz,
  add column if not exists ai_advisor_action_board_source text,
  add column if not exists ai_advisor_action_board_model text,
  add column if not exists ai_advisor_action_board_stale boolean default false;

create table if not exists public.advisor_action_items (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid references public.tenants(id) on delete cascade,
  lead_id uuid not null references public.leads(id) on delete cascade,
  lane_role text not null,
  title text not null,
  description text,
  status text not null default 'open',
  priority text not null default 'medium',
  owner_name text,
  owner_role text,
  due_date timestamptz,
  related_data_room_item_id uuid references public.decision_data_room_items(id) on delete set null,
  client_visible boolean not null default false,
  admin_notes text,
  created_by text,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint advisor_action_items_status_check
    check (status in (
      'open',
      'in_progress',
      'waiting_on_client',
      'waiting_on_advisor',
      'complete',
      'not_needed'
    )),
  constraint advisor_action_items_priority_check
    check (priority in ('low', 'medium', 'high'))
);

create index if not exists advisor_action_items_lead_id_idx
  on public.advisor_action_items (lead_id);

create index if not exists advisor_action_items_tenant_id_idx
  on public.advisor_action_items (tenant_id);

alter table public.advisor_action_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'advisor_action_items'
      and policyname = 'No public access to advisor_action_items'
  ) then
    create policy "No public access to advisor_action_items"
      on public.advisor_action_items
      for all
      using (false);
  end if;
end $$;


-- ========== 018_async_lead_generation_status.sql ==========
-- Async lead generation status tracking

alter table public.leads
  add column if not exists generation_status text default 'intake_received',
  add column if not exists generation_started_at timestamptz,
  add column if not exists generation_completed_at timestamptz,
  add column if not exists generation_error text,
  add column if not exists generation_progress jsonb default '{}'::jsonb,
  add column if not exists base_report_status text default 'pending',
  add column if not exists strategy_room_status text default 'pending',
  add column if not exists decision_layer_status text default 'pending',
  add column if not exists advisor_action_board_status text default 'pending',
  add column if not exists presentation_status text default 'pending';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'leads_generation_status_check'
  ) then
    alter table public.leads
      add constraint leads_generation_status_check
      check (generation_status in (
        'intake_received',
        'generating',
        'partially_ready',
        'complete',
        'failed'
      ));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'leads_base_report_status_check'
  ) then
    alter table public.leads
      add constraint leads_base_report_status_check
      check (base_report_status in ('pending', 'running', 'ready', 'failed', 'skipped'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'leads_strategy_room_status_check'
  ) then
    alter table public.leads
      add constraint leads_strategy_room_status_check
      check (strategy_room_status in ('pending', 'running', 'ready', 'failed', 'skipped'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'leads_decision_layer_status_check'
  ) then
    alter table public.leads
      add constraint leads_decision_layer_status_check
      check (decision_layer_status in ('pending', 'running', 'ready', 'failed', 'skipped'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'leads_advisor_action_board_status_check'
  ) then
    alter table public.leads
      add constraint leads_advisor_action_board_status_check
      check (advisor_action_board_status in ('pending', 'running', 'ready', 'failed', 'skipped'));
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'leads_presentation_status_check'
  ) then
    alter table public.leads
      add constraint leads_presentation_status_check
      check (presentation_status in ('pending', 'running', 'ready', 'failed', 'skipped'));
  end if;
end $$;

create index if not exists leads_generation_status_idx
  on public.leads (generation_status);
