-- Track whether AI report was generated by OpenAI or fallback logic

alter table public.leads
  add column if not exists report_source text
    check (report_source in ('openai', 'fallback'));

create index if not exists leads_report_source_idx on public.leads (report_source);
